plugins:
  bandit:
    enabled: true
  pep8:
    enabled: true
  radon: 
    enabled: true
  fixme:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - tests/**
